compiler:
 - gcc

os:
 - linux
 - osx

env:
  global:
    - QT_PREFIX=$HOME/qt/gcc_64
    - QT_PLUGIN_PATH=$QT_PREFIX/plugins

sudo: required
dist: trusty
osx_image: xcode7.3

cache:
 - apt
 - bundler

before_install:
 - iflin () { if [[ $TRAVIS_OS_NAME == linux ]]; then eval $@; fi; }
 - ifmac () { if [[ $TRAVIS_OS_NAME == osx ]]; then eval $@; fi; }
 - iflin .travis/before-install-linux.sh
 - ifmac .travis/before-install-osx.sh

before_script:
 - iflin $TRAVIS_BUILD_DIR/.travis/lint.sh $TRAVIS_BUILD_DIR
 - iflin source /opt/qt55/bin/qt55-env.sh
 - mkdir BUILD
 - cd BUILD

 - ifmac cmake -G"Xcode" -DCMAKE_PREFIX_PATH=`brew --prefix qt55` -DCMAKE_OSX_DEPLOYMENT_TARGET=10.7 .. --debug-output
 - iflin cmake -DSC_EL=no -DCMAKE_INSTALL_PREFIX:PATH=$PWD/Install -DCMAKE_BUILD_TYPE=Release .. --debug-output
# some paths
 - ifmac export SCLANG=$TRAVIS_BUILD_DIR/BUILD/Install/SuperCollider/SuperCollider.app/Contents/MacOS/sclang
 - iflin export SCLANG=$TRAVIS_BUILD_DIR/BUILD/Install/bin/sclang
# prep for testing
 - sudo pip install git+https://github.com/scztt/qpm.git@qpm-unit
 - qpm quark checkout CommonTests CommonTestsGUI --location $HOME/Quarks
 - cp ../travis_test_run_proto.json ./travis_test_run.json

script:
# build
 - iflin sudo make install
 - ifmac cmake --build . --config Release --target install
# test
 - $TRAVIS_BUILD_DIR/testsuite/sclang/launch_test.py $SCLANG
 - qpm test.run -l ./travis_test_run.json --path $SCLANG --include $HOME/Quarks
# package
 - ifmac mkdir -p $HOME/artifacts
 - (ifmac cd Install; ifmac zip -q -r $HOME/artifacts/SC-$TRAVIS_COMMIT.zip SuperCollider)

before_deploy:
 # required for github releases
 - git fetch --tags
 - export BUILD_PREFIX=$TRAVIS_REPO_SLUG/$TRAVIS_OS_NAME
 - export S3_BUILDS_LOCATION=builds/$BUILD_PREFIX
 - export S3_URL=https://supercollider.s3.amazonaws.com/$S3_BUILDS_LOCATION/SC-$TRAVIS_COMMIT.zip
 - export FWD_HTML='<html><head><meta http-equiv="refresh" content="0; url='$S3_URL'" /></head></html>'
 # put everything to be archived in artifacts/
 - mkdir -p "$HOME/artifacts/${TRAVIS_BRANCH%/*}"
 - mkdir -p "$HOME/artifacts/${TRAVIS_TAG%/*}"
 - echo $FWD_HTML > $HOME/artifacts/$TRAVIS_BRANCH-latest.html
 - 'if [[ $TRAVIS_TAG != "head" ]]; then echo $FWD_HTML > $HOME/artifacts/$TRAVIS_TAG.html; fi;'

deploy:
 # s3 upload - every commit
 - provider: s3
   access_key_id: $AWS_KEY
   secret_access_key: $AWS_SECRET
   bucket: supercollider
   local-dir: $HOME/artifacts
   upload-dir: $S3_BUILDS_LOCATION
   region: us-west-2
   skip_cleanup: true
   endpoint: s3-us-west-2.amazonaws.com
   acl: public_read
   on:
     condition: $TRAVIS_OS_NAME = osx && ! -z $AWS_KEY && ! -z $AWS_SECRET
     all_branches: true
 # github releases - only tags
 - provider: releases
   api_key: $GITHUB_KEY
   file: $HOME/artifacts/SC-$TRAVIS_COMMIT.zip
   prerelease: true
   skip_cleanup: true
   on:
     condition: $TRAVIS_OS_NAME = osx && ! -z $GITHUB_KEY
     tags: true
     all_branches: true
after-deploy:
 - "echo S3 Build Location: $S3_URL"


notifications:
  on_success: change
  on_failure: change
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/51b9b53ca50a7bfca97d
    on_success: change
    on_failure: always
